#!/bin/bash
#####################################################################
# CONVERT_FROM_WEBP by furryfixer
#
# A bash script to convert EITHER or BOTH .webp images or animations
# to other formats.
#  * Will differentiate between still pics and animations
#  * Will process multiple files, allowing mixture of pics/animations
#  * Will average frame delay/duration if variable in webp
#      animations to better approximate original playback speed
# Requires "libwebp-tools" and optionally, libnotify. Basenames or
# full pathnames may be used, but arguments must be files,
# not directories (no recursion). Default ouput formats are:
# PNG for pics and GIF for animations. Change in first two lines 
# if other formats are desired.
#####################################################################

pic_ext="png"        # Format must be understood by libwebp/ convert 
animation_ext="gif"  # Format must be understood by libwebp/ convert

while (( "$#" )); do
   dlay=${DELAY:-0}
   loops=${LOOP:-0}
   sum_dur=0
   full_filename=`realpath $1`
   prefix=`echo -n $full_filename | sed -e 's/^\(.*\).webp$/\1/'`
   [[ -z $prefix ]] && prefix=$full_filename
   basenm=`basename $prefix`
   n=`webpinfo -summary $full_filename | grep frames | sed -e 's/.* \([0-9]*\)$/\1/'`
   if [[ $n -eq 1 ]]; then
      ext=$pic_ext
      dwebp $prefix.webp -o $prefix.$ext
   else
      ext=$animation_ext
      webpinfo -summary $full_filename | grep Duration | sed -e 's/.* \([0-9]*\)$/\1/g' > /tmp/webp_durs
      if [[ $dlay -eq 0 ]]; then
         while read -r dur; do      # sum and average durations if not all same
            sum_dur=$(( $sum_dur+$dur ))
         done < /tmp/webp_durs
         ms_delay=$((sum_dur / n + 5)) # add 5 to round properly below (not floating-point)
         dlay=$((ms_delay / 10))
      fi
      convert -delay $dlay -dispose none $full_filename -coalesce -loop $loops -layers optimize $prefix.$ext
      ext=$animation_ext
   fi
   notify-send "Converted "$basenm".webp to "$basenm"."$ext
   echo "Converted "$basenm".webp to "$basenm.$ext
   shift
done
